/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './category.component';
import * as i4 from './category.service';
const styles_CategoryComponent:any[] = ([] as any[]);
export const RenderType_CategoryComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CategoryComponent,data:{}});
function View_CategoryComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'a',[['class',
      'list-group-item']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        if (('click' === en)) {
          const pd_1:any = ((<any>_co.onCategoryClicked(_v.context.$implicit)) !== false);
          ad = (pd_1 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
      [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'span',[['class','badge']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['','']))],(_ck,
      _v) => {
    const currVal_2:any = i0.ɵinlineInterpolate(1,'/category/',_v.context.$implicit.code,
        '01/1');
    _ck(_v,1,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,1).target;
    const currVal_1:any = i0.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.code_name;
    _ck(_v,2,0,currVal_3);
    const currVal_4:any = _v.context.$implicit.count;
    _ck(_v,4,0,currVal_4);
  });
}
export function View_CategoryComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'list-group']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_CategoryComponent_1)),i0.ɵdid(802816,
          (null as any),0,i2.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        var _co:i3.CategoryComponent = _v.component;
        const currVal_0:any = _co.categories;
        _ck(_v,3,0,currVal_0);
      },(null as any));
}
export function View_CategoryComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-category',
      ([] as any[]),(null as any),(null as any),(null as any),View_CategoryComponent_0,
      RenderType_CategoryComponent)),i0.ɵdid(114688,(null as any),0,i3.CategoryComponent,
      [i4.CategoryService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CategoryComponentNgFactory:i0.ComponentFactory<i3.CategoryComponent> = i0.ɵccf('app-category',
    i3.CategoryComponent,View_CategoryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvY2F0ZWdvcnkvY2F0ZWdvcnkuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvU3R1ZGllcy9Bbmd1bGFyIDIgYW5kIE5vZGVKUy9Gb29kSW5mby9hc3NldHMvYXBwL2NhdGVnb3J5L2NhdGVnb3J5LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvU3R1ZGllcy9Bbmd1bGFyIDIgYW5kIE5vZGVKUy9Gb29kSW5mby9hc3NldHMvYXBwL2NhdGVnb3J5L2NhdGVnb3J5LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvY2F0ZWdvcnkvY2F0ZWdvcnkuY29tcG9uZW50LnRzLkNhdGVnb3J5Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImxpc3QtZ3JvdXBcIj5cclxuICA8YSAqbmdGb3I9XCJsZXQgY2F0ZWdvcnkgb2YgY2F0ZWdvcmllc1wiIHJvdXRlckxpbms9XCIvY2F0ZWdvcnkve3tjYXRlZ29yeS5jb2RlfX0wMS8xXCIgKGNsaWNrKT1cIm9uQ2F0ZWdvcnlDbGlja2VkKGNhdGVnb3J5KVwiIGNsYXNzPVwibGlzdC1ncm91cC1pdGVtXCI+e3tjYXRlZ29yeS5jb2RlX25hbWV9fTxzcGFuIGNsYXNzPVwiYmFkZ2VcIj57e2NhdGVnb3J5LmNvdW50fX08L3NwYW4+PC9hPlxyXG48L2Rpdj4iLCI8YXBwLWNhdGVnb3J5PjwvYXBwLWNhdGVnb3J5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NFO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQW9GO1VBQUE7VUFBQTtRQUFBO1FBQXBGO01BQUEsdUNBQUE7TUFBQTtNQUFBLGVBQWtKLHdDQUFzQjtNQUFBO01BQUEsOEJBQW9COztJQUFySjtRQUFBO0lBQXZDLFdBQXVDLFNBQXZDOztJQUFBO0lBQUE7SUFBQSxXQUFBLG1CQUFBO0lBQWtKO0lBQUE7SUFBMEM7SUFBQTs7OztvQkFEOUw7TUFBQTtNQUF3Qix5Q0FDdEI7VUFBQSxnRUFBQTtVQUFBO1VBQUEsdUNBQXlOOzs7UUFBdE47UUFBSCxXQUFHLFNBQUg7Ozs7b0JDREY7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
