/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './category.component';
import * as i4 from './category.service';
const styles_CategoryComponent:any[] = ([] as any[]);
export const RenderType_CategoryComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CategoryComponent,data:{}});
function View_CategoryComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'a',[['class',
      'list-group-item']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        if (('click' === en)) {
          const pd_1:any = ((<any>_co.onCategoryClicked(_v.context.$implicit.code_name)) !== false);
          ad = (pd_1 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
      [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'span',[['class','badge']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['','']))],(_ck,
      _v) => {
    const currVal_2:any = i0.ɵinlineInterpolate(1,'/category/',_v.context.$implicit.code,
        '01/1');
    _ck(_v,1,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,1).target;
    const currVal_1:any = i0.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.code_name;
    _ck(_v,2,0,currVal_3);
    const currVal_4:any = _v.context.$implicit.count;
    _ck(_v,4,0,currVal_4);
  });
}
export function View_CategoryComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'list-group']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_CategoryComponent_1)),i0.ɵdid(802816,
          (null as any),0,i2.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        var _co:i3.CategoryComponent = _v.component;
        const currVal_0:any = _co.categories;
        _ck(_v,3,0,currVal_0);
      },(null as any));
}
export function View_CategoryComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-category',
      ([] as any[]),(null as any),(null as any),(null as any),View_CategoryComponent_0,
      RenderType_CategoryComponent)),i0.ɵdid(114688,(null as any),0,i3.CategoryComponent,
      [i4.CategoryService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CategoryComponentNgFactory:i0.ComponentFactory<i3.CategoryComponent> = i0.ɵccf('app-category',
    i3.CategoryComponent,View_CategoryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovd29yay9QZXJzb25hbC9mb29kaW5mby9hc3NldHMvYXBwL2NhdGVnb3J5L2NhdGVnb3J5LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi93b3JrL1BlcnNvbmFsL2Zvb2RpbmZvL2Fzc2V0cy9hcHAvY2F0ZWdvcnkvY2F0ZWdvcnkuY29tcG9uZW50LnRzIiwibmc6Ly8vRTovd29yay9QZXJzb25hbC9mb29kaW5mby9hc3NldHMvYXBwL2NhdGVnb3J5L2NhdGVnb3J5LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovd29yay9QZXJzb25hbC9mb29kaW5mby9hc3NldHMvYXBwL2NhdGVnb3J5L2NhdGVnb3J5LmNvbXBvbmVudC50cy5DYXRlZ29yeUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJsaXN0LWdyb3VwXCI+XHJcbiAgPGEgKm5nRm9yPVwibGV0IGNhdGVnb3J5IG9mIGNhdGVnb3JpZXNcIiByb3V0ZXJMaW5rPVwiL2NhdGVnb3J5L3t7Y2F0ZWdvcnkuY29kZX19MDEvMVwiIChjbGljayk9XCJvbkNhdGVnb3J5Q2xpY2tlZChjYXRlZ29yeS5jb2RlX25hbWUpXCIgY2xhc3M9XCJsaXN0LWdyb3VwLWl0ZW1cIj57e2NhdGVnb3J5LmNvZGVfbmFtZX19PHNwYW4gY2xhc3M9XCJiYWRnZVwiPnt7Y2F0ZWdvcnkuY291bnR9fTwvc3Bhbj48L2E+XHJcbjwvZGl2PiIsIjxhcHAtY2F0ZWdvcnk+PC9hcHAtY2F0ZWdvcnk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ0U7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO1VBQUE7Y0FBQTtVQUFBO1FBQUE7UUFBb0Y7VUFBQTtVQUFBO1FBQUE7UUFBcEY7TUFBQSx1Q0FBQTtNQUFBO01BQUEsZUFBNEosd0NBQXNCO01BQUE7TUFBQSw4QkFBb0I7O0lBQS9KO1FBQUE7SUFBdkMsV0FBdUMsU0FBdkM7O0lBQUE7SUFBQTtJQUFBLFdBQUEsbUJBQUE7SUFBNEo7SUFBQTtJQUEwQztJQUFBOzs7O29CQUR4TTtNQUFBO01BQXdCLHlDQUN0QjtVQUFBLGdFQUFBO1VBQUE7VUFBQSx1Q0FBbU87OztRQUFoTztRQUFILFdBQUcsU0FBSDs7OztvQkNERjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
