/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './food-detail.component';
import * as i4 from '../food/food.service';
import * as i5 from './food-detail.service';
const styles_FoodDetailComponent:any[] = ([] as any[]);
export const RenderType_FoodDetailComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FoodDetailComponent,data:{}});
function View_FoodDetailComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.name;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_FoodDetailComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'page-header']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a',([] as any[]),
          [[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,4).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'span',[['aria-hidden',
          'true'],['class','glyphicon glyphicon-chevron-left']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          [' ',''])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['포함된 성분들'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),4,'ul',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
          View_FoodDetailComponent_1)),i0.ɵdid(802816,(null as any),0,i2.NgForOf,[i0.ViewContainerRef,
          i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n\n']))],
      (_ck,_v) => {
        var _co:i3.FoodDetailComponent = _v.component;
        const currVal_2:any = i0.ɵinlineInterpolate(1,'/category/',_co.food_code,'/1');
        _ck(_v,4,0,currVal_2);
        const currVal_4:any = _co.materials;
        _ck(_v,15,0,currVal_4);
      },(_ck,_v) => {
        var _co:i3.FoodDetailComponent = _v.component;
        const currVal_0:any = i0.ɵnov(_v,4).target;
        const currVal_1:any = i0.ɵnov(_v,4).href;
        _ck(_v,3,0,currVal_0,currVal_1);
        const currVal_3:any = _co.getCurrentFoodName();
        _ck(_v,6,0,currVal_3);
      });
}
export function View_FoodDetailComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-food-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_FoodDetailComponent_0,
      RenderType_FoodDetailComponent)),i0.ɵdid(114688,(null as any),0,i3.FoodDetailComponent,
      [i1.ActivatedRoute,i4.FoodService,i5.FoodDetailService],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const FoodDetailComponentNgFactory:i0.ComponentFactory<i3.FoodDetailComponent> = i0.ɵccf('app-food-detail',
    i3.FoodDetailComponent,View_FoodDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvZm9vZC1kZXRhaWwvZm9vZC1kZXRhaWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvU3R1ZGllcy9Bbmd1bGFyIDIgYW5kIE5vZGVKUy9Gb29kSW5mby9hc3NldHMvYXBwL2Zvb2QtZGV0YWlsL2Zvb2QtZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvU3R1ZGllcy9Bbmd1bGFyIDIgYW5kIE5vZGVKUy9Gb29kSW5mby9hc3NldHMvYXBwL2Zvb2QtZGV0YWlsL2Zvb2QtZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvZm9vZC1kZXRhaWwvZm9vZC1kZXRhaWwuY29tcG9uZW50LnRzLkZvb2REZXRhaWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwicGFnZS1oZWFkZXJcIj5cclxuICA8aDE+PGEgcm91dGVyTGluaz1cIi9jYXRlZ29yeS97e2Zvb2RfY29kZX19LzFcIj48c3BhbiBjbGFzcz1cImdseXBoaWNvbiBnbHlwaGljb24tY2hldnJvbi1sZWZ0XCIgYXJpYS1oaWRkZW49XCJ0cnVlXCI+PC9zcGFuPjwvYT4ge3tnZXRDdXJyZW50Rm9vZE5hbWUoKX19PC9oMT5cclxuPC9kaXY+XHJcbjxoMz7tj6ztlajrkJwg7ISx67aE65OkPC9oMz5cclxuPHVsPlxyXG4gICAgPGxpICpuZ0Zvcj1cImxldCBtYXQgb2YgbWF0ZXJpYWxzXCI+e3ttYXQubmFtZX19PC9saT5cclxuPC91bD5cclxuXHJcbiIsIjxhcHAtZm9vZC1kZXRhaWw+PC9hcHAtZm9vZC1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0tJO01BQUEsd0VBQWtDO2FBQUE7SUFBQTtJQUFBOzs7O29CQUx0QztNQUFBO01BQXlCLHlDQUN2QjtVQUFBO1VBQUEsZ0JBQUk7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxlQUEwQztVQUFBO1VBQUEsNENBQTZFO1VBQUEsV0FBOEIsdUNBQ3JKO1VBQUEsU0FDTjtVQUFBO01BQUksNENBQVk7TUFDaEI7VUFBQSwwREFBSTtVQUFBLGFBQ0E7VUFBQSxvQ0FBQTsyQ0FBQTtNQUFtRCx1Q0FDbEQ7OztRQUxJO1FBQUgsV0FBRyxTQUFIO1FBSUU7UUFBSixZQUFJLFNBQUo7OztRQUpFO1FBQUE7UUFBQSxXQUFBLG1CQUFBO1FBQXVIO1FBQUE7Ozs7b0JDRDdIO01BQUE7b0NBQUEsVUFBQTtNQUFBOztRQUFBOzs7OyJ9
