/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'button',
      [['class','btn btn-danger']],(null as any),[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        var _co:i1.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Logout'])),(_l()(),
      i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),['\n    ']))],
      (null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.LogoutComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9UcmluaXR5L1N0dWRpZXMvQW5ndWxhciAyIGFuZCBOb2RlSlMvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1RyaW5pdHkvU3R1ZGllcy9Bbmd1bGFyIDIgYW5kIE5vZGVKUy9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMuTG9nb3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJvbkxvZ291dFwiPkxvZ291dDwvYnV0dG9uPlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLWxvZ291dD48L2FwcC1sb2dvdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLDBEQUFzQztNQUFBLHFCQUNsQztNQUFBO2dCQUFBO1FBQUE7UUFBQTtRQUErQjtVQUFBO1VBQUE7UUFBQTtRQUEvQjtNQUFBLGdDQUFrRCwyQ0FBZTthQUFBLGdDQUMvRDs7OztvQkNIZDtNQUFBO2FBQUE7VUFBQTs7OyJ9
