/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from '@angular/router';
import * as i4 from './category/category.service';
import * as i5 from '@angular/http';
import * as i6 from './food/food.service';
import * as i7 from './food-detail/food-detail.service';
import * as i8 from './search/search.service';
import * as i9 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'app-header',([] as any[]),(null as any),(null as any),(null as any),i1.View_HeaderComponent_0,
          i1.RenderType_HeaderComponent)),i0.ɵdid(49152,(null as any),0,i2.HeaderComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i0.ɵdid(212992,(null as any),
          0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
              [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,8,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵprd(4608,(null as any),i4.CategoryService,i4.CategoryService,[i5.Http]),
      i0.ɵprd(4608,(null as any),i6.FoodService,i6.FoodService,[i5.Http]),i0.ɵprd(4608,
          (null as any),i7.FoodDetailService,i7.FoodDetailService,[i5.Http]),i0.ɵprd(4608,
          (null as any),i8.SearchService,i8.SearchService,[i5.Http]),i0.ɵdid(49152,
          (null as any),0,i9.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i9.AppComponent> = i0.ɵccf('my-app',
    i9.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9UcmluaXR5L1N0dWRpZXMvQW5ndWxhciAyIGFuZCBOb2RlSlMvRm9vZEluZm8vYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVHJpbml0eS9TdHVkaWVzL0FuZ3VsYXIgMiBhbmQgTm9kZUpTL0Zvb2RJbmZvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XHJcbiAgICA8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XHJcbiAgICA8aHI+XHJcbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjwvZGl2PiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO3VDQUFBLFVBQUE7VUFBQSwyQ0FBeUI7VUFBQSxhQUN6QjtVQUFBO01BQUksMkNBQ0o7VUFBQTtVQUFBLG1EQUFBO1VBQUE7Y0FBQTtNQUErQjtJQUEvQjs7OztvQkNISjtNQUFBO2FBQUE7YUFBQTtVQUFBO1VBQUEsa0VBQUE7VUFBQTs7OzsifQ==
